source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               icons/,\
               lib/ast-cli-java-wrapper-2.4.24.jar,\
               lib/jackson-core-2.21.4.jar,\
               lib/jackson-databind-2.21.5.jar,\
               lib/jackson-annotations-2.21.jar,\
               lib/slf4j-api-2.0.17.jar,\
               lib/slf4j-simple-2.0.17.jar,\
               lib/slf4j-reload4j-2.0.17.jar,\
               lib/commons-lang3-3.18.0.jar,\
               .