output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               icons/,\
               lib/org.eclipse.mylyn.commons.ui_4.9.0.v20251121-0615.jar,\
               lib/org-eclipse-mylyn-commons-core.jar,\
               .
source.. = src/
