name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  tag-creation:
    name: Create Release Tag
    permissions:
      contents: write  # for Git to git push
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag
        env:
          TAG_INPUT: ${{ github.event.inputs.tag }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "$TAG_INPUT"
          echo "NEXT_VERSION=$TAG_INPUT" >> $GITHUB_ENV
          tag="$TAG_INPUT"
          message="${TAG_INPUT}: Manual tag creation"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
