name: Nightly Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  set_tag:
    name: Generate Release Tag
    runs-on: cx-public-ubuntu-x64
    outputs:
      tag_name: ${{ steps.tagname.outputs.tag_name }}
    steps:
      - name: Create tagname
        run: echo "tag_name=2.0.0" >> "$GITHUB_OUTPUT"
        id: tagname
      - name: Print tagname
        env:
          TAG_NAME: ${{ steps.tagname.outputs.tag_name }}
        run: echo "created tag $TAG_NAME"
  nightly:
    needs: set_tag
    uses: Checkmarx/ast-eclipse-plugin/.github/workflows/release.yml@a776dbbfa70cda798753bec14dd7c1f47d094595
    with:
      tag: ${{ needs.set_tag.outputs.tag_name }}
      rbranch: "nightly"
