name: Update checkmarx Java wrapper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-checkmarx-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Get Latest Checkmarx Java wrapper version
        id: ast-cli-java-wrapper
        run: |
          echo ::set-output name=release_tag::$(curl -s https://search.maven.org/solrsearch/select?q=g:"com.checkmarx.ast"+AND+a:"ast-cli-java-wrapper" | grep -Po 'latestVersion.:.\K[^"]*')
          echo ::set-output name=current_tag::$(<ast-cli-java-wrapper.version)
      - name: Update Checkmarx Java wrapper version
        if: steps.ast-cli-java-wrapper.outputs.current_tag != steps.ast-cli-java-wrapper.outputs.release_tag
        run: |
          # Update current release
          echo ${{ steps.ast-cli-java-wrapper.outputs.release_tag }} > ast-cli-java-wrapper.version
          current_version=ast-cli-java-wrapper-${{ steps.ast-cli-java-wrapper.outputs.current_tag }}.jar
          new_version=ast-cli-java-wrapper-${{ steps.ast-cli-java-wrapper.outputs.release_tag }}.jar
          sed -i "s/$current_version/$new_version/g" checkmarx-ast-eclipse-plugin/build.properties
          sed -i "s/$current_version/$new_version/g" checkmarx-ast-eclipse-plugin/.classpath
          sed -i "s/$current_version/$new_version/g" checkmarx-ast-eclipse-plugin/META-INF/MANIFEST.MF
          cd checkmarx-ast-eclipse-plugin/lib/
          rm -rf "$current_version"
          curl "https://repo1.maven.org/maven2/com/checkmarx/ast/ast-cli-java-wrapper/${{ steps.ast-cli-java-wrapper.outputs.release_tag }}/${new_version}" --output $new_version
      - name: Create Pull Request
        if: steps.ast-cli-java-wrapper.outputs.current_tag != steps.ast-cli-java-wrapper.outputs.release_tag
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update ast-cli-java-wrapper to ${{ steps.ast-cli-java-wrapper.outputs.release_tag }}
          title: Update ast-cli-java-wrapper with ${{ steps.ast-cli-java-wrapper.outputs.release_tag }}
          body: |
            Updates [ast-cli-java-wrapper][1] to ${{ steps.ast-cli-java-wrapper.outputs.release_tag }}
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/CheckmarxDev/ast-cli-java-wrapper
          labels: dependencies, automated pr
          branch: feature/update_java_wrapper 
