name: Update checkmarx Java wrapper
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-checkmarx-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          lfs: true

      - name: Install Git LFS
        run: git lfs install

      - name: Configure Git user
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com

      - name: Get Latest Checkmarx Java wrapper version
        id: ast-cli-java-wrapper
        run: |
          echo "release_tag=$(curl -s \"https://repo1.maven.org/maven2/com/checkmarx/ast/ast-cli-java-wrapper/maven-metadata.xml\" | grep -oPm1 \"(?<=<latest>)[^<]+\")" >> $GITHUB_OUTPUT
          echo "current_tag=$(<ast-cli-java-wrapper.version)" >> $GITHUB_OUTPUT

      - name: Update Checkmarx Java wrapper version
        if: steps.ast-cli-java-wrapper.outputs.current_tag != steps.ast-cli-java-wrapper.outputs.release_tag
        run: |
          # Update current release
          echo "${{ steps.ast-cli-java-wrapper.outputs.release_tag }}" > ast-cli-java-wrapper.version
          current_version="ast-cli-java-wrapper-${{ steps.ast-cli-java-wrapper.outputs.current_tag }}.jar"
          new_version="ast-cli-java-wrapper-${{ steps.ast-cli-java-wrapper.outputs.release_tag }}.jar"
          sed -i "s/$current_version/$new_version/g" checkmarx-ast-eclipse-plugin/build.properties
          sed -i "s/$current_version/$new_version/g" checkmarx-ast-eclipse-plugin/.classpath
          sed -i "s/$current_version/$new_version/g" checkmarx-ast-eclipse-plugin/META-INF/MANIFEST.MF

          # Remove old JAR and download the new one
          cd checkmarx-ast-eclipse-plugin/lib/
          rm -f "$current_version"
          curl -o "$new_version" "https://repo1.maven.org/maven2/com/checkmarx/ast/ast-cli-java-wrapper/${{ steps.ast-cli-java-wrapper.outputs.release_tag }}/$new_version"

          # Track the new JAR file with LFS
          FILE_PATH="checkmarx-ast-eclipse-plugin/lib/$new_version"
          git lfs track "$FILE_PATH"
          git add .gitattributes "$FILE_PATH"
          git commit -m "Update ast-cli-java-wrapper to ${{ steps.ast-cli-java-wrapper.outputs.release_tag }}"
          git push origin HEAD:${{ github.ref }}

      - name: Create Pull Request
        if: env.current_tag != env.release_tag
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c #v6.1.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: Update ast-cli-java-wrapper to ${{ env.release_tag }}
          title: Update ast-cli-java-wrapper with ${{ env.release_tag }}
          body: |
            Updates [ast-cli-java-wrapper][1] to ${{ env.release_tag }}
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/CheckmarxDev/ast-cli-java-wrapper
          labels: cxone
          branch: dependency/update_java_wrapper
